services:
  db:
    image: postgres:16-alpine
    container_name: cinema-db
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema
    # 5433 снаружи, чтобы не конфликтовать с локальным Postgres, если он появится
    ports:
      - "5433:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema -d cinema"]
      interval: 5s
      timeout: 3s
      retries: 10
