"""directors

Revision ID: d59688a7d2aa
Revises: 3065bb313559
Create Date: 2026-09-05 09:04:32.493891+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd59688a7d2aa'
down_revision: str | None = '3065bb313559'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('directors', postgresql.ARRAY(sa.String(length=128)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'directors')
    # ### end Alembic commands ###
