"""single mark per film

Revision ID: 8d50db0a8788
Revises: d59688a7d2aa
Create Date: 2026-09-05 12:09:54.511352+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8d50db0a8788'
down_revision: str | None = 'd59688a7d2aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Новая причина снятия: отметку вытеснила вторая кнопка.
    # CHECK пересобираем вручную — autogenerate таких изменений не видит.
    op.drop_constraint("revoke_reason", "interests", type_="check")
    op.create_check_constraint(
        "revoke_reason",
        "interests",
        "revoke_reason IN ('manual', 'expired', 'watched', 'superseded')",
    )

    # Состояния стали взаимоисключающими. Там, где у человека на одном фильме
    # активны обе отметки, оставляем «Ближайшее» — оно свежее и весит больше,
    # а «Желаемое» снимаем. Без этого не создастся новый уникальный индекс.
    op.execute(
        """
        UPDATE interests AS w
        SET revoked_at = now(), revoke_reason = 'superseded'
        WHERE w.kind = 'wishlist'
          AND w.revoked_at IS NULL
          AND EXISTS (
              SELECT 1 FROM interests AS s
              WHERE s.user_id = w.user_id
                AND s.film_id = w.film_id
                AND s.kind = 'soon'
                AND s.revoked_at IS NULL
          )
        """
    )

    # На всякий случай: если где-то остались дубли одного вида (индекс раньше
    # их допускал по разным kind), оставляем самую свежую отметку.
    op.execute(
        """
        UPDATE interests AS older
        SET revoked_at = now(), revoke_reason = 'superseded'
        WHERE older.revoked_at IS NULL
          AND EXISTS (
              SELECT 1 FROM interests AS newer
              WHERE newer.user_id = older.user_id
                AND newer.film_id = older.film_id
                AND newer.revoked_at IS NULL
                AND (newer.created_at, newer.id) > (older.created_at, older.id)
          )
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk_watches_film_id_films')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_watches_screening_id_screenings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watches_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watches')),
    sa.UniqueConstraint('user_id', 'film_id', name='uq_watch')
    )
    op.create_index(op.f('ix_watches_film_id'), 'watches', ['film_id'], unique=False)
    op.create_index(op.f('ix_watches_user_id'), 'watches', ['user_id'], unique=False)
    op.drop_index('uq_interests_active', table_name='interests', postgresql_where='(revoked_at IS NULL)')
    op.create_index('uq_interests_active', 'interests', ['user_id', 'film_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("revoke_reason", "interests", type_="check")
    op.create_check_constraint(
        "revoke_reason",
        "interests",
        "revoke_reason IN ('manual', 'expired', 'watched')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_interests_active', table_name='interests', postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('uq_interests_active', 'interests', ['user_id', 'film_id', 'kind'], unique=True, postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('ix_watches_user_id'), table_name='watches')
    op.drop_index(op.f('ix_watches_film_id'), table_name='watches')
    op.drop_table('watches')
    # ### end Alembic commands ###
