"""referrals

Revision ID: 373d6eb3a37a
Revises: 551017554ce9
Create Date: 2026-09-05 21:08:13.292511+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '373d6eb3a37a'
down_revision: str | None = '551017554ce9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk_referrals_film_id_films')),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], name=op.f('fk_referrals_invitee_id_users')),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('fk_referrals_referrer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('invitee_id', 'film_id', name='uq_referral')
    )
    op.create_index(op.f('ix_referrals_film_id'), 'referrals', ['film_id'], unique=False)
    op.create_index(op.f('ix_referrals_invitee_id'), 'referrals', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_invitee_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_film_id'), table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
