"""initial schema

Revision ID: 3065bb313559
Revises: 
Create Date: 2026-09-04 19:34:39.700781+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3065bb313559'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Триграммный индекс поиска по названиям (ix_films_title_trgm) без этого
    # расширения не создастся.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_halls'))
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('stage', sa.Enum('collecting', 'shortlist_review', 'slot_voting', 'schedule_review', 'published', 'running', 'closed', name='round_stage', native_enum=False, create_constraint=True, length=32), server_default='collecting', nullable=False),
    sa.Column('shortlist_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('low_activity', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds')),
    sa.UniqueConstraint('week_start', name=op.f('uq_rounds_week_start'))
    )
    op.create_index(op.f('ix_rounds_stage'), 'rounds', ['stage'], unique=False)
    op.create_table('tmdb_sync_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_tmdb_sync_state'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('user', 'moderator', 'admin', 'superadmin', name='user_role', native_enum=False, create_constraint=True, length=32), server_default='user', nullable=False),
    sa.Column('tz', sa.String(length=64), server_default='Europe/Moscow', nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('tg_id', name=op.f('uq_users_tg_id'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_table('autopilot_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_autopilot_proposals_round_id_rounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autopilot_proposals')),
    sa.UniqueConstraint('round_id', 'stage', name='uq_autopilot_round_stage')
    )
    op.create_index(op.f('ix_autopilot_proposals_round_id'), 'autopilot_proposals', ['round_id'], unique=False)
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('kp_id', sa.Integer(), nullable=True),
    sa.Column('title_ru', sa.String(length=512), nullable=False),
    sa.Column('title_orig', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('runtime_min', sa.Integer(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('backdrop_path', sa.String(length=255), nullable=True),
    sa.Column('trailer_key', sa.String(length=64), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('ext_rating', sa.Float(), nullable=True),
    sa.Column('ext_votes', sa.Integer(), nullable=True),
    sa.Column('kp_rating', sa.Float(), nullable=True),
    sa.Column('kp_votes', sa.Integer(), nullable=True),
    sa.Column('kp_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'hidden', 'pending_moderation', name='film_status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('tmdb_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_films_added_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_films')),
    sa.UniqueConstraint('kp_id', name=op.f('uq_films_kp_id'))
    )
    op.create_index('ix_films_status_year', 'films', ['status', 'year'], unique=False)
    op.create_index('ix_films_title_trgm', 'films', ['title_ru', 'title_orig'], unique=False, postgresql_using='gin', postgresql_ops={'title_ru': 'gin_trgm_ops', 'title_orig': 'gin_trgm_ops'})
    op.create_index(op.f('ix_films_tmdb_id'), 'films', ['tmdb_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('soon_expired', 'shortlist_published', 'schedule_published', 'screening_changed', 'screening_cancelled', 'reminder_24h', 'reminder_2h', 'waitlist_promoted', 'feedback_reminder', 'no_show', 'late_cancel', 'film_request_resolved', 'admin_shortlist_ready', 'admin_matrix_ready', 'admin_autopilot_ran', 'admin_low_attendance', 'admin_cancel_request', 'admin_film_request', name='notification_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedup_key', name='uq_notifications_dedup_key')
    )
    op.create_index('ix_notifications_user_unsent', 'notifications', ['user_id', 'sent_at'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_settings_updated_by_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), server_default='180', nullable=False),
    sa.Column('blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], name=op.f('fk_slots_hall_id_halls')),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_slots_round_id_rounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slots')),
    sa.UniqueConstraint('round_id', 'hall_id', 'starts_at', name='uq_slot_slot')
    )
    op.create_index(op.f('ix_slots_round_id'), 'slots', ['round_id'], unique=False)
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_availability_round_id_rounds')),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_availability_slot_id_slots')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_availability_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability')),
    sa.UniqueConstraint('round_id', 'user_id', 'slot_id', name='uq_availability')
    )
    op.create_index('ix_availability_round_slot', 'availability', ['round_id', 'slot_id'], unique=False)
    op.create_table('film_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_title', sa.String(length=512), nullable=False),
    sa.Column('raw_year', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='film_request_status', native_enum=False, create_constraint=True, length=32), server_default='pending', nullable=False),
    sa.Column('resolved_film_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_film_requests_resolved_by_users')),
    sa.ForeignKeyConstraint(['resolved_film_id'], ['films.id'], name=op.f('fk_film_requests_resolved_film_id_films')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_film_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_requests'))
    )
    op.create_index(op.f('ix_film_requests_status'), 'film_requests', ['status'], unique=False)
    op.create_index(op.f('ix_film_requests_user_id'), 'film_requests', ['user_id'], unique=False)
    op.create_table('film_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk_film_votes_film_id_films')),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_film_votes_round_id_rounds')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_film_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_film_votes')),
    sa.UniqueConstraint('round_id', 'user_id', 'film_id', name='uq_vote')
    )
    op.create_index('ix_film_votes_round_film', 'film_votes', ['round_id', 'film_id'], unique=False)
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('wishlist', 'soon', name='interest_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Enum('manual', 'expired', 'watched', name='revoke_reason', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('expiry_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk_interests_film_id_films')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interests'))
    )
    op.create_index('ix_interests_film_active', 'interests', ['film_id', 'revoked_at'], unique=False)
    op.create_index('ix_interests_user_active', 'interests', ['user_id', 'revoked_at'], unique=False)
    op.create_index('uq_interests_active', 'interests', ['user_id', 'film_id', 'kind'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', 'completed', name='screening_status', native_enum=False, create_constraint=True, length=32), server_default='scheduled', nullable=False),
    sa.Column('expected_attendance', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('attendance_secret', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_screenings_decided_by_users')),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk_screenings_film_id_films')),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_screenings_round_id_rounds')),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_screenings_slot_id_slots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screenings'))
    )
    op.create_index(op.f('ix_screenings_film_id'), 'screenings', ['film_id'], unique=False)
    op.create_index(op.f('ix_screenings_round_id'), 'screenings', ['round_id'], unique=False)
    op.create_index('uq_screening_round_film', 'screenings', ['round_id', 'film_id'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    op.create_index('uq_screening_slot', 'screenings', ['slot_id'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    op.create_table('shortlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('auto_weight', 'auto_coverage', 'admin', name='shortlist_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weight_snapshot', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk_shortlist_items_film_id_films')),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_shortlist_items_round_id_rounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortlist_items')),
    sa.UniqueConstraint('round_id', 'film_id', name='uq_shortlist_round_film')
    )
    op.create_index(op.f('ix_shortlist_items_round_id'), 'shortlist_items', ['round_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('qr', 'code', 'manual', name='attendance_method', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('marked_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name=op.f('fk_attendance_marked_by_users')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_attendance_screening_id_screenings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attendance_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('screening_id', 'user_id', name='uq_attendance')
    )
    op.create_index(op.f('ix_attendance_screening_id'), 'attendance', ['screening_id'], unique=False)
    op.create_table('cancel_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_cancel_requests_approved_by_users')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_cancel_requests_requested_by_users')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_cancel_requests_screening_id_screenings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cancel_requests'))
    )
    op.create_index(op.f('ix_cancel_requests_screening_id'), 'cancel_requests', ['screening_id'], unique=False)
    op.create_table('confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('confirmed', 'waitlist', 'cancelled', name='confirmation_state', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('was_late_cancel', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reminded_24h_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_2h_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_confirmations_screening_id_screenings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_confirmations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confirmations')),
    sa.UniqueConstraint('screening_id', 'user_id', name='uq_confirmation')
    )
    op.create_index('ix_confirmations_screening_state', 'confirmations', ['screening_id', 'state'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('film_rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('org_sound', sa.Integer(), nullable=True),
    sa.Column('org_picture', sa.Integer(), nullable=True),
    sa.Column('org_hall', sa.Integer(), nullable=True),
    sa.Column('org_time', sa.Integer(), nullable=True),
    sa.Column('org_comment', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('film_rating IS NULL OR film_rating BETWEEN 1 AND 10', name=op.f('ck_feedback_film_rating_range')),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk_feedback_film_id_films')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_feedback_screening_id_screenings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('screening_id', 'user_id', name='uq_feedback')
    )
    op.create_index(op.f('ix_feedback_film_id'), 'feedback', ['film_id'], unique=False)
    op.create_index(op.f('ix_feedback_screening_id'), 'feedback', ['screening_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_screening_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_film_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_confirmations_screening_state', table_name='confirmations')
    op.drop_table('confirmations')
    op.drop_index(op.f('ix_cancel_requests_screening_id'), table_name='cancel_requests')
    op.drop_table('cancel_requests')
    op.drop_index(op.f('ix_attendance_screening_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_shortlist_items_round_id'), table_name='shortlist_items')
    op.drop_table('shortlist_items')
    op.drop_index('uq_screening_slot', table_name='screenings', postgresql_where=sa.text("status <> 'cancelled'"))
    op.drop_index('uq_screening_round_film', table_name='screenings', postgresql_where=sa.text("status <> 'cancelled'"))
    op.drop_index(op.f('ix_screenings_round_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_film_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_index('uq_interests_active', table_name='interests', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_interests_user_active', table_name='interests')
    op.drop_index('ix_interests_film_active', table_name='interests')
    op.drop_table('interests')
    op.drop_index('ix_film_votes_round_film', table_name='film_votes')
    op.drop_table('film_votes')
    op.drop_index(op.f('ix_film_requests_user_id'), table_name='film_requests')
    op.drop_index(op.f('ix_film_requests_status'), table_name='film_requests')
    op.drop_table('film_requests')
    op.drop_index('ix_availability_round_slot', table_name='availability')
    op.drop_table('availability')
    op.drop_index(op.f('ix_slots_round_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_table('settings')
    op.drop_index('ix_notifications_user_unsent', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_films_tmdb_id'), table_name='films')
    op.drop_index('ix_films_title_trgm', table_name='films', postgresql_using='gin', postgresql_ops={'title_ru': 'gin_trgm_ops', 'title_orig': 'gin_trgm_ops'})
    op.drop_index('ix_films_status_year', table_name='films')
    op.drop_table('films')
    op.drop_index(op.f('ix_autopilot_proposals_round_id'), table_name='autopilot_proposals')
    op.drop_table('autopilot_proposals')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('tmdb_sync_state')
    op.drop_index(op.f('ix_rounds_stage'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_table('halls')
    # ### end Alembic commands ###
