"""manual events

Revision ID: 551017554ce9
Revises: 8d50db0a8788
Create Date: 2026-09-05 14:01:21.330873+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '551017554ce9'
down_revision: str | None = '8d50db0a8788'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Условие частичного индекса изменилось, а autogenerate таких правок не видит.
    # Ручные события не участвуют в правиле «один фильм за цикл»: у них нет ни
    # цикла, ни обязательного фильма, и без этого NULL-ы ломали бы индекс.
    op.drop_index("uq_screening_round_film", table_name="screenings")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('is_manual', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('screenings', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('screenings', sa.Column('note', sa.Text(), nullable=True))
    op.alter_column('screenings', 'round_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('screenings', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('slots', 'round_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(
        "uq_screening_round_film",
        "screenings",
        ["round_id", "film_id"],
        unique=True,
        postgresql_where=sa.text(
            "status <> 'cancelled' AND round_id IS NOT NULL AND film_id IS NOT NULL"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slots', 'round_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('screenings', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('screenings', 'round_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('screenings', 'note')
    op.drop_column('screenings', 'title')
    op.drop_column('screenings', 'is_manual')
    # ### end Alembic commands ###
