import type { FilmBrief, FilmCard, User } from "./types";

export const MOCK_USERS: Record<string, User> = {
  student: {
    id: 101,
    display_name: "Даниил Киселёв",
    tg_username: "cu_student",
    photo_url: null,
    role: "user",
    access: true,
  },
  club_member: {
    id: 102,
    display_name: "Александра Смирнова",
    tg_username: "smirnova_cu",
    photo_url: null,
    role: "moderator",
    access: true,
  },
  host: {
    id: 103,
    display_name: "Михаил Романов",
    tg_username: "mikhail_host",
    photo_url: null,
    role: "admin",
    access: true,
  },
  admin: {
    id: 1,
    display_name: "Кир | Jeki",
    tg_username: "jeki_cu",
    photo_url: null,
    role: "superadmin",
    access: true,
  },
};

export const MOCK_FILMS: FilmBrief[] = [
  {
    id: 1,
    tmdb_id: 157336,
    title_ru: "Интерстеллар",
    title_orig: "Interstellar",
    year: 2014,
    poster_url: "https://image.openmoviedb.com/kinopoisk-images/1600647/4301e953-2940-421e-9276-857c0f1e8e50/orig",
    genres: ["фантастика", "драма", "приключения"],
    directors: ["Кристофер Нолан"],
    in_catalog: true,
    my_interests: ["wishlist"],
    can_renew_soon: false,
    soon_expires_at: null,
    watched: false,
  },
  {
    id: 2,
    tmdb_id: 27205,
    title_ru: "Начало",
    title_orig: "Inception",
    year: 2010,
    poster_url: "https://image.openmoviedb.com/kinopoisk-images/1629390/8ab9a119-dd74-44f0-baec-0629797418d7/orig",
    genres: ["фантастика", "боевик", "триллер"],
    directors: ["Кристофер Нолан"],
    in_catalog: true,
    my_interests: ["soon"],
    can_renew_soon: false,
    soon_expires_at: null,
    watched: true,
  },
  {
    id: 3,
    tmdb_id: 496243,
    title_ru: "Паразиты",
    title_orig: "Gisaengchung",
    year: 2019,
    poster_url: "https://image.openmoviedb.com/kinopoisk-images/1599028/0b76b2a2-d1c7-4f04-a284-80ff7bb709a4/orig",
    genres: ["триллер", "драма", "комедия"],
    directors: ["Пон Джун-хо"],
    in_catalog: true,
    my_interests: ["wishlist"],
    can_renew_soon: false,
    soon_expires_at: null,
    watched: false,
  },
  {
    id: 4,
    tmdb_id: 120467,
    title_ru: "Одержимость",
    title_orig: "Whiplash",
    year: 2014,
    poster_url: "https://image.openmoviedb.com/kinopoisk-images/1600647/947477c7-0130-4e00-9852-675003c2ff5d/orig",
    genres: ["драма", "музыка"],
    directors: ["Дэмьен Шазелл"],
    in_catalog: true,
    my_interests: [],
    can_renew_soon: false,
    soon_expires_at: null,
    watched: false,
  },
  {
    id: 5,
    tmdb_id: 550,
    title_ru: "Бойцовский клуб",
    title_orig: "Fight Club",
    year: 1999,
    poster_url: "https://image.openmoviedb.com/kinopoisk-images/1900788/87b565bf-a797-4aec-949a-e156cf0f35d8/orig",
    genres: ["триллер", "драма", "криминал"],
    directors: ["Дэвид Финчер"],
    in_catalog: true,
    my_interests: [],
    can_renew_soon: false,
    soon_expires_at: null,
    watched: true,
  },
  {
    id: 6,
    tmdb_id: 335984,
    title_ru: "Бегущий по лезвию 2049",
    title_orig: "Blade Runner 2049",
    year: 2017,
    poster_url: "https://image.openmoviedb.com/kinopoisk-images/1773646/d6d7c865-c344-469b-986c-7f516a8b79fb/orig",
    genres: ["фантастика", "детектив", "драма"],
    directors: ["Дени Вильнёв"],
    in_catalog: true,
    my_interests: ["wishlist"],
    can_renew_soon: false,
    soon_expires_at: null,
    watched: false,
  },
];

export const MOCK_FILM_DETAIL: FilmCard = {
  ...MOCK_FILMS[0],
  runtime_min: 169,
  overview:
    "Когда засуха, пыльные бури и вымирание растений приводят человечество к продовольственному кризису, коллектив исследователей и учёных отправляется сквозь червоточину в поисках нового дома.",
  trailer_key: "qcPfI0y7wRU",
  kp_rating: 8.6,
  kp_votes: 1100000,
  tmdb_rating: 8.4,
  tmdb_votes: 35000,
  internal_rating: 4.9,
  internal_votes: 42,
  interested_count: 58,
  invited_by: null,
  my_rating: 5,
  reviews: [
    {
      author: "Александра Смирнова",
      rating: 5,
      text: "Один из лучших научно-фантастических фильмов XXI века. Саундтрек Ханса Циммера на университетском звуке пробирает до мурашек!",
      created_at: "2026-09-08T19:30:00Z",
    },
    {
      author: "Михаил Романов",
      rating: 4.5,
      text: "Отличный выбор для киноклуба: после сеанса устроили полуторачасовое обсуждение релятивистской физики и теории струн.",
      created_at: "2026-09-07T21:15:00Z",
    },
  ],
};

export const MOCK_ACTIVE_SCREENING = {
  id: 42,
  movie_title: "Интерстеллар",
  movie_year: 2014,
  poster_url: "https://image.openmoviedb.com/kinopoisk-images/1600647/4301e953-2940-421e-9276-857c0f1e8e50/orig",
  date_formatted: "Пятница, 13 сентября • 19:00",
  hall: "Аудитория 402 (Кинозал CU)",
  total_seats: 45,
  confirmed_seats: 38,
  waitlist_count: 6,
  status: "confirmed" as const,
  user_ticket: {
    status: "CONFIRMED" as const,
    seat_label: "Ряд 3, Место 7",
    verification_code: "CU-7482",
  },
};
